- drivers/media/pci/intel/ipu6/ipu-resources.c
UBSAN is default enabled on 5.15 kernel on Ubuntu. The code to
allocate resources in IPU can cause some array-index-out-of-bounds
and shift-out-of-bounds warnings, so it needs to be fixed.
> media: pci: intel: Avoid UBSAN warnings of index bound and shift

- drivers/media/i2c/hi556.c
- drivers/media/i2c/hm11b1.c
- drivers/media/i2c/hm2170.c
- drivers/media/i2c/ov01a10.c
- drivers/media/i2c/ov01a1s.c
- drivers/media/i2c/ov02c10.c
- drivers/media/i2c/ov13858_intel.c
- drivers/media/i2c/ov2740.c
- drivers/media/i2c/ov8856.c
Closes: #54
Signed-off-by: You-Sheng Yang (vicamo) <vicamo.yang@canonical.com>
> backport: accommodate to i2c remove callback return void

- drivers/media/pci/intel/ipu-isys-csi2-be-soc.c
- drivers/media/pci/intel/ipu-isys-csi2.c
- drivers/media/pci/intel/ipu-isys-queue.c
- drivers/media/pci/intel/ipu-isys-subdev.c
- drivers/media/pci/intel/ipu-isys-video.c
- drivers/media/pci/intel/ipu.h
- drivers/media/pci/intel/ipu6/ipu6-isys-csi2.c
Fix compilation with kernel 6.1, deal with the media-controller changes which have landed in 6.1-rc2.
Closes: #63
Signed-off-by: Hans de Goede <hdegoede@redhat.com>
> Fix compilation with kernel 6.1

- drivers/media/pci/intel/ipu-bus.c
- drivers/media/pci/intel/ipu-bus.h
- drivers/media/pci/intel/ipu.c
This fixes a crash on a ThinkPad X1 Yoga Gen 7 in the following scenario (which happens every boot!):
1. intel-ipu6 gets loaded by udev based on its PCI modalias
2. ipu_pci_probe() exits with -EPROBE_DEFER because the int3472 driver for the power-ctrl has not loaded yet
3. intel-ipu6-isys + intel-ipu6-psys get loaded by udev based on the PCI modaliases they contain
4. intel-ipu6-isys + intel-ipu6-psys register their ipu_bus_driver-s with ipu_bus_register_driver()
5. ipu_pci_probe() exits with -EPROBE_DEFER a couple more times
6. udev loads the int3472 driver
7. ipu_pci_probe() no longer hits a path resulting -EPROBE_DEFER, instead it calls ipu_psys_init()
8. ipu_psys_init() calls ipu_bus_add_device(psys), which immediately causes the intel-ipu6-psys driver, which has already been …
> Fix crash due to ipu_psys_probe() dereferencing isp->pkg_dir before ipu_pci_probe() sets it

- drivers/media/pci/intel/ipu-psys.c
Linux kernels >= 6.2 need drivers to either explicitly take the dma-buf-reservation lock themselves; or they need to call the _unlocked variant of various dmabuf functions to do this for them.
See upstream linux commit ae2e7f28a170c01f ("dma-buf: Document dynamic locking convention") for details.
This fixes the following crashes with 6.2:
```
[ 2038.884232] ------------[ cut here ]------------
[ 2038.884240] WARNING: CPU: 6 PID: 5873 at drivers/dma-buf/dma-buf.c:1120 dma_buf_map_attachment+0x92/0x120
[ 2038.884246] Modules linked in: snd_seq_dummy snd_hrtimer qrtr bnep binfmt_misc snd_ctl_led snd_soc_skl_hda_dsp snd_soc_intel_hda_dsp_common snd_sof_probes snd_soc_hdac_hdmi snd_soc_dmic iTCO_wdt intel_pmc_bxt iTCO_vendor_support mei_pxp mei_hdcp gpio_ljca(O) spi_ljca(O) i2c_ljca(O) …
```
> Fix dmabuf errors with kernel 6.2

- drivers/media/pci/intel/ipu.c
Devices must not be renamed after they have already been added to the device hierarchy.
dev_set_name() MUST only be called before dev_add() and the pci_dev passed to ipu_pci_probe() has been added long before ipu_pci_probe() runs, so it must not rename it.
Renaming it is confusing udevd which now all of a sudden sees a device it already knows about change name.
This is causing udev rules to not work properly with the ipu6-driver. Drop the clearly wrong dev_set_name() call.
> Don't rename the already registered PCI-device

- drivers/media/pci/intel/ipu-psys.c
Resloves ipu-psys: MODULE_IMPORT_NS(DMA_BUF) for kernel 5.15 #77
> psys: fix compilation issue on kernel 5.15

- drivers/media/pci/intel/ipu-isys-subdev.c
Following support for MEDIA_BUS_FMT_Y8_1X8:
ipu_isys_mbus_code_to_bpp
ipu_isys_mbus_code_to_mipi
Link validation fix.
> ipu6-isys-subdev: add Y8 to mbus code conversion functions.

- drivers/media/pci/intel/ipu-isys-subdev.c
isys subdev link validataion cause kernel exception for index out of bound when Y8 code used for streaming.
> isys-subdev: add Y8 media format

- drivers/media/pci/intel/ipu.c
For MTL ES2, something is wrong with the devTLB invalidation for IPU, it will cause the transaction between IPU and IOMMU failure. Once vt-d enabled in the system, it will cause system hang. Solution is to disable the PCI ATS for IPU which was enabled by default.
Test Platform:
mtlrvp
rex-ES2
> iotg mtl alpha release v1.0.1 - media/ipu6: disable the ATS for IPU6 on MTL ES2

- .github/workflows/test.yml
- drivers/media/pci/intel/cio2-bridge.c
- drivers/media/pci/intel/cio2-bridge.h
Fix cio2-bridge compilation with kernel 6.3 and later.
> cio2-bridge: Fix compilation with kernel >= 6.3

- drivers/media/i2c/hm11b1.c
- drivers/media/i2c/ov01a1s.c
- drivers/media/i2c/ov2740.c
- patch/int3472-support-independent-clock-and-LED-gpios-5.17+.patch
- patch/int3472-support-independent-clock-and-LED-gpios.patch
Starting with kernel 6.1.7 this commit is upstream:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=cf5ac2d45f6e4d11ad78e7b10ae9a4121ba5e995
"platform/x86: int3472/discrete: Ensure the clk/power enable pins are in output mode"
This fixes a bug which was causing the INT3472 to not work correctly in some cases.
With this fixed it is possible to use the ipu6-drivers sensor drivers with an unmodified upstream kernel by switching to the clk-framework for clk-control as done by other upstream drivers in combination with fixing the polarity of the reset + powerdown signals and making the privacy-led GPIO optional.
> Make IPU6 sensors code work with unpatched upstream kernels >= 6.1.7

- 0001-Add-the-camera-sensor-gc5035-to-support-ADL-M.patch
- Makefile
- drivers/media/i2c/Makefile
- drivers/media/i2c/gc5035.c
- drivers/media/pci/intel/cio2-bridge.c
The sensor driver was updated to support several features:
1. Add acpi to support x86 platform
2. Add some resolutions/control and more regs specifically for ADL-M.
3. Add gpio pins supported by int3272 and power on the sensor.
4. v4l2 support.
5. Adapt to intel IPU6-drivers, like 3A.
The sensor driver gc5035 is modified based on the following link:
https://patchwork.kernel.org/project/linux-media/patch/20200902224813.14283-4-tfiga@chromium.org
and also IPU6-drivers to support the new sensor.
Regarding to the patch-0001-Add-the-camera-sensor-gc5035-to-support-ADL-M.patch
, which need to patch to kernel6.1.y and compile it inside.
> Add the sensor gc5035 to support ADL-M.

- .github/workflows/test.yml
- drivers/media/pci/intel/ipu-isys-video.c
Add a video_nr module parameter so that the isys /dev/video# node can be assigned a fixed number instead of taking the first available free number.
Both Ubuntu and Fedora by default use the IPU6 camera stack together with v4l2loopback for compat with apps which expect a regular video4linux2 device.
Most apps open /dev/video0 by default so we want that to be the v4l2loopback device. But currently if the ipu6-drivers load first they become /dev/video0.
This new video_nr module parameter allows distros to specify a different fixed number for intel_ipu6_isys so that v4l2loopback becomes /dev/video0 independent of the probe ordering.
> intel_ipu6_isys: Add video_nr module parameter

- drivers/media/pci/intel/ipu-isys-queue.c
there are 2 video for image and meta, clear both pipes. get ipu_isys_pipeline from media_pipe, as image and meta share one pipeline.
when stop 2 av of image and meta, only need to reset 1 time.
> media: intel-ipu6: isys reset for case has meta data

- drivers/media/pci/intel/ipu.c
ipu_pci_probe() did not call ipu_buttress_exit() on fw load errors, causing the following oops when trying to load the module a second time (rmmod + modprobe) after installing the firmware:
```
[  717.471913] sysfs: cannot create duplicate filename '/devices/pci0000:00/0000:00:05.0/psys_fused_min_freq'
[  717.471917] CPU: 3 PID: 2535 Comm: modprobe Tainted: G           OE      6.4.0-rc6+ #11
[  717.471920] Hardware name: Default string Default string/Default string, BIOS JP2V1.09 07/29/2022
[  717.471923] Call Trace:
[  717.471928]  <TASK>
[  717.471932]  dump_stack_lvl+0x71/0x90
[  717.471941]  sysfs_warn_dup+0x56/0x70
[  717.471948]  sysfs_add_file_mode_ns+0x12d/0x140
[  717.471953]  sysfs_create_file_ns+0x4f/0x70
[  717.471958]  ipu_buttress_init+0x326/0x490 [intel_ipu6]
[  717.471975] …
```
> ipu6: Fix ipu_buttress_exit() not being called on fw load failure

- drivers/media/i2c/ov02c10.c
Change Description:
OV02C10 with module names CJFME32 and 2BG203N3
are rotated 180 degrees from others,
so we will need to manaully do a rotation
within sensor driver
Test Platform:
MTL-P
> media: i2c: rotate 180 for some OV02C10 modules

- patch/int3472-v6.5/0001-platform-x86-int3472-Add-handshake-GPIO-function.patch
Control Logic driver INT3472 needs to add handshake GPIO function for Lattice
Handshake pin is used for Lattice MIPI aggregator to enable the
camera sensor. After pulled up, recommend to wail ~250ms to get
everything ready.
Patch summited to community for review
https://lore.kernel.org/all/20231007021225.9240-1-hao.yao@intel.com/
> Add int3472 kernel patch for 6.5

- drivers/media/i2c/ov2740.c
On probe() the ov2740 code was manually setting the reset GPIO instead of using the power_on() helper function.
This path however left out enabling the clk, which power_on() does do, so when power_off() runs after the probe() is done (on runtime suspend) then there are 2 ugly backtraces triggered by WARN()s in the clk-core. One for "clk already disabled" followed by one for "clk already unprepared".
Fix this by using the power_on() helper in probe().
> media: ov2740: Fix "clk already disabled" / "already unprepared" oops / backtraces

- drivers/media/i2c/hi556.c
- drivers/media/i2c/hm2172.c
- drivers/media/i2c/ov02e10.c
Lattice MIPI aggregator with some version FW needs longer delay after handshake triggered. We set 25ms as a safe value and wait for a stable version FW.
> media: i2c: Extends the delay to 25 ms

- drivers/media/i2c/gc5035.c
- drivers/media/i2c/hi556.c
- drivers/media/i2c/hm11b1.c
- drivers/media/i2c/hm2170.c
- drivers/media/i2c/hm2172.c
- drivers/media/i2c/ov01a10.c
- drivers/media/i2c/ov01a1s.c
- drivers/media/i2c/ov02c10.c
- drivers/media/i2c/ov02e10.c
- drivers/media/i2c/ov08a10.c
- drivers/media/i2c/ov2740.c
- drivers/media/i2c/ov8856.c
- drivers/media/pci/intel/ipu-isys.c
- drivers/media/pci/intel/ipu6/ipu6-isys-phy.c
- include/media/ipu-isys.h
Kernel 6.6 has made some significant changes to how v4l2-async (sub)dev registration works. Adjust the code accordingly.
Note this is based on building against a recent verison of the media_staging/master git tree. Since 6.6 has not been released yet there is a small chance that there might be some more work needed, but this should at least make things work with 6.6-rc1 once released.
> ipu6: Fix compilation with kernels >= 6.6.0

- drivers/media/pci/intel/cio2-bridge.c
CIO2 driver doesn't add new sensor OV08X40's information, so need to bind the camera sensor to IPU6 as a subdevice
> media/pci: Add sensor OV08X40 information for IPU6

- drivers/media/pci/intel/cio2-bridge.c
- drivers/media/pci/intel/cio2-bridge.h
Here is a set of 3 fixes to make ipu6-drivers work with the 6.7 and 6.8 kernels
1. The first commit fixes the ipu6-isys driver crashing (due to a bug in a cleanup on error paths) after a failure in isys_probe() (this fixes #205)
2. The second commit fixes the drivers not compiling against kernel 6.8
3. The third commit fixes the kernel crashing with kernel 6.8 due to the cio2-bridge code making the .name attribute of 2 long-lived software_nodes point to on stack memory
Cc: @vicamo @smallorange
> Ipu6 kernel 6.7 and 6.8 fixes

- drivers/media/i2c/ov02c10.c
- drivers/media/i2c/ov2740.c
Galaxy Book4 Pro uses OV02C10, and it needed some additional fixes to make it work.
> Fix Galaxy Book4 Pro compatibility

- drivers/media/i2c/ov2740.c
It is sufficient for 1 of the link-frequencies reported in the bus-cfg to match with one of the link-frequencies from the link-freq menu.
This fixes the ipu6-driver version of the ov2740 driver not working when combined with the in kernel version of the ipu-bridge code.
> ov2740: Fix link-frequency check

- drivers/media/i2c/ov05c10.c
Refine the soft standby register setting to ensure the proper functionality of stream-off/stream-on operations
> media: ov05c10: Update streaming on/off register settings

- Makefile
- dkms.conf
- drivers/media/i2c/Makefile
- drivers/media/i2c/gc5035.c
Here is a set with 4 Makefile improvements:
- Makefile: Switch sensor driver symbols from CONFIG_VIDEO_FOO to CONFIG_ICAMERA_FOO
- Makefile: Re-enable gc5035 compilation with kernels >= 6.8
- Makefile: Do not build hi556 driver with kernels >= 6.10
- Makefile: Do not build ov01a10 driver with kernels >= 6.8
> IPU6 makefile fixes

- drivers/media/pci/intel/ipu6/psys/ipu-psys.c
- drivers/media/pci/intel/ipu6/psys/ipu-psys.h
- drivers/media/pci/intel/ipu6/psys/ipu6-ppg.c
- drivers/media/pci/intel/ipu6/psys/ipu6-psys.c
- patches/0001-v6.10-IPU6-headers-used-by-PSYS.patch
Upstream commit daabc5c64703 ("media: ipu6: not override the dma_ops of device in driver") has changed the ipu6-bus code to no longer modify the aux device's dma_ops, instead new ipu6_dma_*() helpers were introduced modify the psys driver to use these new helpers.
This fixes a DMA WARN_ON() triggering, which was followed by ipu6_psys_probe() failing due to dma_alloc_attrs() failing.
Cc: @vicamo @bingbucao
> ipu6-psys: Adjust DMA code for ipu6-bus DMA changes in kernels >= 6.12

- drivers/media/pci/intel/ipu6/psys/ipu-psys.c
The new auxbus code-paths were not registering the ipu_psys_bus used for
psys->dev.bus = &ipu_psys_bus, this was causing udev to not be able to
properly enumerate the device. For example running:
```
udevadm test -a add /dev/ipu-psys0
```
would fail with the following error:
```
Failed to clone sd_device object: No such file or directory
```
This udev issue in turn was causing issues with udev rules to set
permissions on /dev/ipu-psys0 not working
Fix this by:
1. Rename ipu6_psys_bus to ipu_psys_bus, there is no need for separate
names for this struct with different kernels and having the same name
allows code sharing.
2. Switching back from using module_auxiliary_driver() to using
module_init() / module_exit() codes for registering the drivers.
3. Move the now always used ipu_psys_init() …
> psys: Do not skip registering ipu_psys_bus for kernels >= 6.10

- drivers/media/i2c/isx031.c
- drivers/media/i2c/ov2311.c
- drivers/media/i2c/ti953-ser.c
- drivers/media/i2c/ti953.h
- drivers/media/i2c/ti960-des.c
- drivers/media/i2c/ti960-reg.h
- drivers/media/pci/intel/ipu-isys.c
- drivers/media/pci/intel/ipu.c
- drivers/media/platform/intel/ipu6-acpi-common.c
- drivers/media/platform/intel/ipu6-acpi-pdata.c
- drivers/media/platform/intel/ipu6-acpi.c
- drivers/media/platform/intel/ipu6-adlrvp-pdata.c
- drivers/media/platform/intel/ipu6-tglrvp-pdata.c
- include/media/ipu-acpi-pdata.h
- include/media/ipu-acpi.h
- include/media/ov2311.h
- include/media/ti960.h
1. decouple i2c and acpi dependency when ipu6 probe.
2. enhance isx031 mode transition stability.
> 25ww18 release

- drivers/media/pci/intel/ipu6/psys/ipu-psys.c
- drivers/media/pci/intel/ipu6/psys/ipu-psys.h
- drivers/media/pci/intel/ipu6/psys/ipu6-ppg.c
- drivers/media/pci/intel/ipu6/psys/ipu6-psys.c
- kernel_patches/patch_6.12_mainline/0015-lt6911-2-pads-linked-to-ipu-2-ports-for-split-mode.patch
- kernel_patches/patch_6.12_mainline/0016-media-i2c-add-dv_timings-api-in-lt6911uxe_for_ecg_kernel.patch
- kernel_patches/patch_6.12_mainline/0017-media-intel-ipu6-use-vc1-dma-for-MTL-and-ARL.patch
- kernel_patches/patch_6.12_mainline/0019-media-i2c-update-format-in-irq-for-lt6911uxe.patch
- kernel_patches/patch_6.12_mainline/0031-media-ipu-Dma-sync-at-buffer_prepare-callback-as-DMA.patch
- kernel_patches/patch_6.12_mainline/0032-Support-IPU6-ISYS-FW-trace-dump-for-upstream-driver.patch
- kernel_patches/patch_6.12_mainline/0033-Support-IPU6-PSYS-FW-trace-dump-for-upstream-driver.patch
- kernel_patches/patch_6.12_mainline/0034-media-pci-The-order-of-return-buffers-should-be-FIFO.patch
- kernel_patches/patch_6.12_mainline/0036-media-i2c-fix-power-on-issue-for-on-board-LT6911UXE.patch
- kernel_patches/patch_6.12_mainline/README
0017-media-intel-ipu6-use-vc1-dma-for-MTL-and-ARL.patch
0031-media-ipu-Dma-sync-at-buffer_prepare-callback-as-DMA.patch
0032-Support-IPU6-ISYS-FW-trace-dump-for-upstream-driver.patch
0033-Support-IPU6-PSYS-FW-trace-dump-for-upstream-driver.patch
0034-media-pci-The-order-of-return-buffers-should-be-FIFO.patch
0036-media-i2c-fix-power-on-issue-for-on-board-LT6911UXE.patch
> ARL MR2, TWL MR1, ASL MR4 releases on kernel 6.12 Ubuntu 24.04 (iot)
