intel/ipu6-drivers

drivers/media/pci/intel/ipu-bus.c
Signed-off-by: Ignacio Hernandez <ignacio.hernandez@gmail.com>
=> Fix build error for kernel 5.15

.github/workflows/test.yml
Add automated testing of dkms builds against several kernels
=> Automation2

drivers/media/pci/intel/ipu-psys-compat32.c, drivers/media/pci/intel/ipu-psys.c, drivers/media/pci/intel/ipu.c
=> fix ftbfs against v5.18

drivers/media/pci/intel/Makefile, drivers/media/pci/intel/ipu-dma.c, drivers/media/pci/intel/ipu-fw-com.c, drivers/media/pci/intel/ipu-isys-queue.c, drivers/media/pci/intel/ipu-isys-video.c, drivers/media/pci/intel/ipu-isys.c, drivers/media/pci/intel/ipu-psys.c, drivers/media/pci/intel/ipu-trace.c, drivers/media/pci/intel/ipu-trace.h, drivers/media/pci/intel/ipu.c, drivers/media/pci/intel/ipu6/ipu-resources.c, drivers/media/pci/intel/ipu6/ipu6-psys.c, include/media/ipu-isys.h
=> Engineer drop on 2022-06-24

README.md, drivers/media/i2c/ov01a1s.c, drivers/media/pci/intel/ipu-isys-csi2.c, drivers/media/pci/intel/ipu-isys-queue.c, drivers/media/pci/intel/ipu-isys-video.c, drivers/media/pci/intel/ipu-psys.c, drivers/media/pci/intel/ipu6/ipu6-isys-csi2.c, drivers/media/pci/intel/ipu6/ipu6-isys-dwc-phy.c
=> Engineer release on 2022-09-26

patch/media-i2c-Enable-hi556-with-iVSC-5.17+.patch
Close: #46
Signed-off-by: You-Sheng Yang (vicamo) <vicamo.yang@canonical.com>
=> patch: add hi556 patch for kernel v5.17+

.github/workflows/test.yml
This commit enables the daily build of the driver against several kernels. That will help detect when kernel changes (as opposed to commits to this git) break the build process.
=> Automation3

drivers/media/i2c/hm11b1.c, drivers/media/i2c/hm2170.c, drivers/media/i2c/ov01a10.c, drivers/media/i2c/ov01a1s.c, drivers/media/i2c/ov02c10.c, drivers/media/i2c/ov13858_intel.c, drivers/media/i2c/ov2740.c, drivers/media/i2c/ov8856.c, drivers/media/pci/intel/ipu-buttress.c, drivers/media/pci/intel/ipu-buttress.h, drivers/media/pci/intel/ipu-dma.c, drivers/media/pci/intel/ipu-isys-csi2.c, drivers/media/pci/intel/ipu-isys-queue.c, drivers/media/pci/intel/ipu-isys-video.c, drivers/media/pci/intel/ipu-isys-video.h, drivers/media/pci/intel/ipu-psys.c, drivers/media/pci/intel/ipu-psys.h, drivers/media/pci/intel/ipu-trace.c, drivers/media/pci/intel/ipu.c
=> Oasis PV release on 2022-11-12

.github/workflows/test.yml
=> test: Add building against more kernel

Makefile, README.md, drivers/media/pci/intel/Kconfig, drivers/media/pci/intel/cio2-bridge.c, drivers/media/pci/intel/cio2-bridge.h, drivers/media/pci/intel/ipu-isys.c, include/media/ipu-isys.h, patch.diff
=> Meteor Lake platform Alpha release on 2023-01-10

drivers/media/i2c/d4xx.c, drivers/media/i2c/ti960-des.c, drivers/media/i2c/ti960-reg.h, drivers/media/pci/intel/ipu-isys-csi2-be-soc.c, drivers/media/pci/intel/ipu-isys-queue.c, drivers/media/pci/intel/ipu-isys-video.c, drivers/media/pci/intel/ipu-isys.c, drivers/media/pci/intel/ipu-psys.c, include/media/ipu-isys.h
RS engineer release #4: support RS format
Signed-off-by: zouxiaoh <xiaohong.zou@intel.com>
=> RS engineer release #4: support RS format

.github/workflows/test.yml
=> test: Update workflow script

drivers/media/pci/intel/ipu-psys.c
With kernel 6.2 the following possible deadlock gets reported:
```
[  765.679269] ====================================================== [  765.679270] WARNING: possible circular locking dependency detected
[  765.679271] 6.2.0-rc5+ #40 Tainted: G           O
[  765.679272] ------------------------------------------------------
[  765.679272] camerasrc0:src/6354 is trying to acquire lock:
[  765.679273] ffff992aa6ad8158 (&mm->mmap_lock){++++}-{3:3}, at: ipu_dma_buf_map+0x16c/0x400 [intel_ipu6_psys]
[  765.679281]
but task is already holding lock:
[  765.679282] ffff992aa6059dc8 (reservation_ww_class_mutex){+.+.}-{3:3}, at: dma_buf_map_attachment_unlocked+0x3d/0x90
[  765.679286]
which lock already depends on the new lock.
[  765.679287]
the existing dependency chain (in reverse order) is: …
```
=> ipu6-psys: Fix possible deadlock with kernel 6.2

drivers/media/i2c/hm11b1.c, drivers/media/i2c/hm2170.c, drivers/media/i2c/ov01a10.c, drivers/media/i2c/ov01a1s.c, drivers/media/i2c/ov02c10.c, drivers/media/i2c/ov13858_intel.c, drivers/media/i2c/ov2740.c, drivers/media/i2c/ov8856.c, drivers/media/pci/intel/cio2-bridge.c, drivers/media/pci/intel/cio2-bridge.h, drivers/media/pci/intel/ipu-bus.c, drivers/media/pci/intel/ipu-bus.h, drivers/media/pci/intel/ipu-fw-isys.h, drivers/media/pci/intel/ipu-isys-csi2-be-soc.c, drivers/media/pci/intel/ipu-isys-csi2-be.c, drivers/media/pci/intel/ipu-isys-csi2.c, drivers/media/pci/intel/ipu-isys-queue.c, drivers/media/pci/intel/ipu-isys-subdev.c, drivers/media/pci/intel/ipu-isys-video.c, drivers/media/pci/intel/ipu-isys.c, drivers/media/pci/intel/ipu-psys.c, drivers/media/pci/intel/ipu.c, drivers/media/pci/intel/ipu.h, drivers/media/pci/intel/ipu6/Makefile, drivers/media/pci/intel/ipu6/ipu6-isys-csi2.c
=> Engineer release on 2023-02-08

patch_5.19_mainline/0003-int3472-Add-LT6911UXC-support-to-INT3472-driver.patch, patch_6.x_intel-next/0001-iommu-add-in-MTL-P-PCI-ID-for-passthrough-iommu.patch, patch_6.x_intel-next/0001-iommu-intel-ipu-use-IOMMU-passthrough-mode-for-Intel.patch, patch_6.x_intel-next/0002-platform-x86-intel-Support-lt6911uxc-by-INT3472.patch, patch_6.x_intel-next/0003-int3472-Add-LT6911UXC-support-to-INT3472-driver.patch
Signed-off-by: zouxiaoh <xiaohong.zou@intel.com>
=> iotg rpl pv release

drivers/media/i2c/d4xx.c
Fix Y12I broken resolution: change 1600x1300 to 1280x800
=> d4xx: Fix Y12I

drivers/media/i2c/d4xx.c
add imu control handler so it can be registered within isys.
Please confirm. @zouxiaoh
=> d4xx: imu support for IPU6 and LibRealSense

drivers/media/i2c/d4xx.c
changed character device name to be fetched by LibRealSense.
Please approve @zouxiaoh
=> d4xx: dfu multi camera support for ipu6.

drivers/media/i2c/d4xx.c
Fixing start stop sensor operations.
=> d4xx: cleanup start/stop stream operations.

drivers/media/i2c/d4xx.c, drivers/media/pci/intel/ipu-isys-csi2-be-soc.c, drivers/media/pci/intel/ipu-isys-csi2.c, drivers/media/pci/intel/ipu-isys-queue.c, drivers/media/pci/intel/ipu-isys-subdev.c, drivers/media/pci/intel/ipu-isys-video.c, drivers/media/pci/intel/ipu.c, drivers/media/platform/intel/ipu6-acpi-pdata.c
=> iotg rpl mr1 release

drivers/media/i2c/hm2172.c, drivers/media/i2c/ov02e10.c
Add IVSC handshake support for OV02E and HM2172
=> media: i2c: Add IVSC handshake support

drivers/media/i2c/ar0234.c, drivers/media/i2c/d4xx.c, drivers/media/i2c/hm11b1.c, drivers/media/i2c/imx390.c, drivers/media/i2c/lt6911uxc.c, drivers/media/i2c/lt6911uxe.c, drivers/media/i2c/ov01a10.c, drivers/media/i2c/ov01a1s.c, drivers/media/i2c/ov02c10.c, drivers/media/i2c/ov13858_intel.c, drivers/media/i2c/ov8856.c, drivers/media/i2c/ti960-des.c, drivers/media/i2c/ti964.c, drivers/media/pci/intel/ipu-isys-csi2-be-soc.c, drivers/media/pci/intel/ipu-isys-csi2-be.c, drivers/media/pci/intel/ipu-isys-csi2.c, drivers/media/pci/intel/ipu-isys-queue.c, drivers/media/pci/intel/ipu-isys-queue.h, drivers/media/pci/intel/ipu-isys-subdev.c, drivers/media/pci/intel/ipu-isys-subdev.h, drivers/media/pci/intel/ipu-isys-tpg.c, drivers/media/pci/intel/ipu-isys-video.c, drivers/media/pci/intel/ipu-isys-video.h, drivers/media/pci/intel/ipu-isys.c, drivers/media/pci/intel/ipu-mmu.c, drivers/media/pci/intel/ipu-psys.c, drivers/media/pci/intel/ipu.c, drivers/media/platform/intel/ipu6-acpi-pdata.c, drivers/media/platform/intel/ipu6-acpi.c
=> mtl-p mr1 release

patch/v6.8/0006-mei-vsc-reset-ivsc-during-shutdown.patch
ivsc fix on MTL for 6.8 kernel.
=> ivsc fix on MTL

patch/v6.8/0007-mei-vsc-Don-t-stop-restart-mei-device-during-system-.patch, patch/v6.8/0008-mei-vsc-Prevent-timeout-error-with-added-delay-post-.patch, patch/v6.8/0009-media-ivsc-csi-don-t-count-privacy-on-as-error.patch, patch/v6.8/0010-media-ivsc-csi-add-separate-lock-for-v4l2-control-ha.patch, patch/v6.8/0011-media-ivsc-csi-remove-privacy-status-in-struct-mei_c.patch
backport more IVSC patches to kernel 6.8 for MTL
=> patch: v6.8: backport more ivsc patches for MTL

kernel_patches/patch_6.12_mainline/0019-media-i2c-update-format-in-irq-for-lt6911uxe.patch, kernel_patches/patch_6.12_mainline/0020-media-i2c-remove-unused-func-in-lt6911uxe.patch, kernel_patches/patch_6.12_mainline/README
=> MTL MR3 & RPL-P MR2 releases on kernel 6.12.15 Ubuntu 24.04 (iot)

kernel_patches/patch_6.12_mainline/0003-media-pci-intel-update-ipu6-psys-driver.patch, kernel_patches/patch_6.12_mainline/README
=> ARL MR1, TWL MR1, ASL MR4 releases on kernel 6.12 Ubuntu 24.04 (iot)

kernel_patches/patch_6.12_mainline/0057-fix-S4-issue-on-TWL.patch, kernel_patches/patch_6.12_mainline/0058-code-changes-for-link-frequency-and-sensor-physical-.patch, kernel_patches/patch_6.12_mainline/README
0057-fix-S4-issue-on-TWL.patch
0058-code-changes-for-link-frequency-and-sensor-physical-.patch
=> add patches for isx031 + max9296 for kernel v6.12.15
